### PR TITLE
Timer fix

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
Related to #21 , but this PR is a better solution I think.

1. The TimerBase has problems. If you calls the stop method while the callback is in execution, the TimeTask isn't deleted and it continues executing forever (because Kha removes the activeTimer while it is executing, and add it again to the queue if the callback function in `addBreakableTimeTaskToGroup` returns `true`);

2. CallLaterBase and `addFrameTask` doesn't work like that. The second parameter is `priority`, not `delay`. And it returns a `taskid`, that it should be removed when the callback is executed. But it has the same problem that I have described in the first point.

3. If you calls `callLater` from another callLater's callback, then Kha is executing the `kha.Scheduler.executeTimeTasks` method in infinite loop, because it executes the tasks while the length > 0 ( `while(kha_Scheduler.timeTasks.length > 0)`). So, it doesn't finish never. We need a real `haxe.Timer.delay` call at least.

### CODE REVIEW

**Comment by sh-dave** [comment]
I just checked some other backend (i think openfl) to see what it does and it just ran the callback once, without the option to cancel it. Feel free to close my PR.

**Comment by aW4KeNiNG** [comment]
Yes, it should run once. The problem is `addFrameTask` or `addTimeTask` runs forever if you don't stop it :)

Thanks anyway for your PR. Just I notice the problem when I was working/checking in the animation system.

**Comment by sh-dave** [comment]
Only `addFrameTask` runs forever, `addTimeTask` will stop after X runs if the 3. `period` parameter is 0 and only run once if the 4. `duration` parameter is also 0. This is what my PR did.

**Comment by aW4KeNiNG** [comment]
Thanks, you are right.

I have modified the code. Still we need the `haxe.Timer.delay` because the third point. I'm not Kha expert, so, do you know a better solution?

Maybe we shouldn't use `addTimeTask`, just the `haxe.Timer.delay` to avoid the problem.

Regards.

**Comment by aW4KeNiNG** [comment]
Just to be clear. the next code is a infinite loop in Kha (unresponsive app):

```
function runNextKeyframe() {
    applyKeyframe();
    new CallLater(runNextKeyframe);
}

new CallLater(runNextKeyframe);
```

**Comment by sh-dave** [comment]
Delay is the 2. `start` parameter. Setting it to 0 will result in the callback firing next frame. Maybe that already fixes the issue? `period` is when you want to to execute something periodically.

```haxe
Scheduler.addTimeTask(something, 0); // fire next frame only

Scheduler.addTimeTask(something, 0, 1 / 20, 0); // fire indefinitly, 20 times per second

Scheduler.addTimeTask(something, 1.0, 1 / 60, 3.0); // fire with a delay of 1s, 60 times per second, for 3s
```

Also @robdangerous wired haxe.Timer up to use kha.Scheduler internally.

**Comment by aW4KeNiNG** [comment]
Thanks @sh-dave ;) 

`Scheduler.addTimeTask(fn, 0.001);` works perfect.

**Pull request merged**
