### PR TITLE
Make top components resize with the main window

### PR DESCRIPTION
**Pull request by maxfish**
This is an attempt to fix issue #41, mimicking the resizeListener from haxeui-HTML5.

It works as expected, but I'm pretty sure I don't know enough about how haxeui-kha (and haxeui in general) deals with all the different targets.

### CODE REVIEW

**Comment by ianharrigan** [comment]
I think this is fine personally, when the "screen" resizes, the top level components do. I wonder if there is a better way in kha to know when the container / canvas / window resizes though?

**Comment by maxfish** [comment]
I went straight with JS even if there is a function in the [Window class](https://github.com/Kode/Kha/blob/82fcff98a2158f7383250e7285cdd573cb6461ec/Sources/kha/Window.hx#L19) that does exactly that:
`public function notifyOnResize(callback: Int->Int->Void): Void;`

I just didn't know how to access the Kha window from ScreenImpl.hx 😕

**Comment by ianharrigan** [comment]
Yeah, the window class looks perfect - do you have any idea how you would access that in a normal, non-haxeui, application?

**Comment by maxfish** [comment]
I'm preparing a PR for Kha since a change is required in the library, notifyOnResize is only implemented for the Kore backend.
If that goes through then we can change this repo. If not I'll probably look elsewhere for a working UI :-(

**Comment by maxfish** [comment]
Here is the PR https://github.com/Kode/Kha/pull/1198

**Pull request closed without merging**
